# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x08trab5rpc\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"3\n\x0c\x43ommandReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nleader_url\x18\x02 \x01(\t\"\x1f\n\nLogRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"*\n\x08LogReply\x12\x1e\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\r.trab5rpc.Log\"\x16\n\x03Log\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t2\x8e\x01\n\nApiService\x12\x45\n\x0frequest_command\x12\x18.trab5rpc.CommandRequest\x1a\x16.trab5rpc.CommandReply\"\x00\x12\x39\n\x0brequest_log\x12\x14.trab5rpc.LogRequest\x1a\x12.trab5rpc.LogReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=23
  _globals['_COMMANDREQUEST']._serialized_end=56
  _globals['_COMMANDREPLY']._serialized_start=58
  _globals['_COMMANDREPLY']._serialized_end=109
  _globals['_LOGREQUEST']._serialized_start=111
  _globals['_LOGREQUEST']._serialized_end=142
  _globals['_LOGREPLY']._serialized_start=144
  _globals['_LOGREPLY']._serialized_end=186
  _globals['_LOG']._serialized_start=188
  _globals['_LOG']._serialized_end=210
  _globals['_APISERVICE']._serialized_start=213
  _globals['_APISERVICE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
